### ISSUE TITLE
Get timestamp of packet

### ISSUE THREAD

**Issue by Rigstor** [UnaNancyOwen/VelodyneCapture#1]
Hi!

Is there a way to extract the timestamp of the packets with this solution?

**Comment by UnaNancyOwen** [comment]
No, TimeStamp is not implemented yet.

**Comment by Rigstor** [comment]
Ok,

Thanks for the info, if you implement it, please, let me know

**Comment by UnaNancyOwen** [comment]
@Rigstor I was implemented it.
This time is Unix time (microseconds) when packet was received.
Note: The each lasers that included in one frame have different time-stamp, because these are received by multiple packets. If you want to retrieve time-stamp of frame, Please retrieve time of first laser (azimuth = 0, id = 0).

```cpp
while( capture.isRun() ){
    std::vector<velodyne::Laser> lasers;
    capture >> lasers;
    if( lasers.empty() ){
        continue;
    }

    // Sort Laser Data ( 0 degree -> 359 degree, 0 id -> n id )
    std::sort( lasers.begin(), lasers.end() );

    //  Retrieve Laser Time Stamp ( microseconds )
    for( const velodyne::Laser& laser : lasers ){
        const long long laser_time = laser.time;
    }

    // Retrieve Frame Time Stamp ( microseconds )
    const long long frame_time = lasers[0].time;
}
```
