### ISSUE TITLE
Expected expression

### ISSUE THREAD

**Issue by kavinat** [UnaNancyOwen/VelodyneCapture#6]
@UnaNancyOwen I wanted to use this sample to view an HDL-32 pcap file but I am getting an "expected expression"  error in VelodyneCapture.h Line 232. Kindly let me know how to fix it. 

Because of this error the main.cpp is not able to recognise the HDL32E capture class.

**Comment by UnaNancyOwen** [comment]
@kavinat Perhaps, You didn't defined either <code>HAVE_BOOST</code> and <code>HAVE_PCAP</code>.  
In order to use this class, You need to define at least one <code>HAVE_*</code> according to your purpose.  
Please read [ReadMe](https://github.com/UnaNancyOwen/VelodyneCapture#environment) and CMakeLists (sample/simple/CMakeLists.txt [#L19-L31](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/simple/CMakeLists.txt#L19-L31), [#L53](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/simple/CMakeLists.txt#L53), [#L38-L43](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/simple/CMakeLists.txt#L38-L43), [#L54](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/simple/CMakeLists.txt#L54)).


By the way, Are you using CMake to generate project? If you not using CMake, I can't more support. 
If you don't have sufficient knowledge about C++ and CMake, I recommend learn about these before use this class.
