### ISSUE TITLE
sys/time.h missing

### ISSUE THREAD

**Issue by kavinat** [UnaNancyOwen/VelodyneCapture#8]
@UnaNancyOwen  VelodyneCapture.h uses pcap.h which has sys/time.h as an included header file. But when I am trying to build my project on visual studio it says sys/time.h is missing.

Upon further research I got to know that sys.time.h is a POSIX header and not a part of C++ standard library. So how can I use VelodyneCapture.h in a C++ program on visual studio? 

The alternatives according to internet is #include(ctime) but I canot alter pcap.h. Kindly help. 

Environment used:
opencv 3.3.0
VS 2015
PCL 1.8.1
winpcap

**Comment by UnaNancyOwen** [comment]
@kavinat I don't know why require sys/time.h.
It is written in pcap.h of WinPCAP as follows.
Normally, pcap-static.h will be loaded in Windows environment, because WIN32 is defined in Win32 application. sys/time.h would be requested only in UN*X environment.
```cpp
#if defined(WIN32)
  #include <pcap-stdinc.h>
#elif defined(MSDOS)
  #include <sys/types.h>
  #include <sys/socket.h>  /* u_int, u_char etc. */
#else /* UN*X */
  #include <sys/types.h>
  #include <sys/time.h>
#endif /* WIN32/MSDOS/UN*X */
```
The short answer is please define WIN32 in preprocessor. (But, It should already be defined.)
And, This is not bug tracker of WinPCAP. I can't answer questions about WinPCAP.
